### ISSUE TITLE
Add support for chained converters

### ISSUE THREAD

**Issue by Thinkscape** [BorisMoore/jsrender#127]
Converters are a simple concept, but they often will be used in chains (together), especially when used for sanitization, escaping and security-related tasks (like XSS protection). This is how they're implemented in common server-side templating engines (i.e. Twig or Smarty)

For example, I might define several escaper converters and then mix them in different parts of markup. 

Very simple use case:
````js
$.views.converters({
    htmlEscape: function(text){ return $('<span/>').text(text).html(); },
    trim: function(text){ return text.substr(0,10) + '...'; }
});

$.templates({
    chainedExample: ' <img src="http://foo.com/img.gif" alt="{{htmlEscape:trim:title}}" /> '
});

$(document.body).append(
    $.render.chainedExample({ title: "Sam&Max Hit The Road"})
);
````

Expected result:
````html
<img src="http://foo.com/img.gif" alt="Sam&amp;Max Hi..." />
````

What happens instead:
````
"SyntaxError: "Unexpected token :" 
Error in compiled template code:
var j=j||jQuery.views,c=j._convert,ret; try{

return " <img src=\"http://foo.com/img.gif\" alt=\""+c("htmlEscape",view,this,data.trim:data.title)+"\" /> ";

}catch(e){return j._err(e);}"
````

**Comment by BorisMoore** [comment]
Closing "After V1.0" issues for now - to reopen as appropriate.
