### ISSUE TITLE
Add support for #count property

### ISSUE THREAD

**Issue by Thinkscape** [BorisMoore/jsrender#131]
Please add `#count` property, complementary to `#index` which allows for count-related branching.

Typical use case:

````js
$.views.templates({ test:'
    {{if #count == 0}}
        There are no items.
    {{else}}
        {{if #count == 1}}
            This is the only item you will see.
        {{/if}}

        {{:#index}}.  {{:name}} {{:age}}
    {{/if}}
'});
````

**Comment by maxsdw** [comment]
I think this also apply on the case I want to get how many properties are inside an object, for instance, I have and array of objects which I'm iterating on using {{ for }}, and inside each iteration I need to know the length of the object being iterated:

{{for options}}
  <option {{if #count() < 1 }}disabled{{/if}}>...</option>
{{/for}}

**Comment by BorisMoore** [comment]
Closing "After V1.0" issues for now - to reopen as appropriate.
