### ISSUE TITLE
Can't access a variable in {{for}}

### ISSUE THREAD

**Issue by kojilab** [BorisMoore/jsrender#136]
Hi Boris,

I am passing the following to the template
{'items': items, ranked: true}

items is an array of objects

In my template, I have 

{{for items}}
  {{if (ranked)}}{{:#index}}{{/if}}
{{/for}}

But it seems the variable 'ranked' doesn't do anything.

**Comment by Krish2215** [comment]
I have a jquery datatable where I'm displaying child rows using js render. For both the columns on the table the data is coming from 2 different arrays. So how should I break the data into 2 separate rows which is currently displaying as comma separated list

**Comment by BorisMoore** [comment]
@Krish2215: This is for reporting bugs and other issues, not for general help questions. You could try stackoverflow https://stackoverflow.com/questions/tagged/jsrender. But you will need to give much more specific context, and ideally a jsfiddle to show your exact difficulty....
