### ISSUE TITLE
Nested "{{for}}" loop issue?

### ISSUE THREAD

**Issue by AMKohn** [BorisMoore/jsrender#142]
Hi,
I am trying to put together a template with jsRender instead of my own version that I was on, but,  I keep getting a: "Uncaught JsRender Error: Syntax error Unmatched or missing tag: "{{/for}}" in template:" error followed by my entire template (maybe it should just be the template name instead, it gets pretty long).

Here is a truncated version of my code, any ideas as to what is going on? Or is it just the nested for loops?

``` html
<div class="page" id="{{:info.id+info.name}}">
    {{for sources}}
    <header class="feed-title">
        <div class="feed-title-content">
            <span class="feed-title-text">{{:title}}</span>
        </div>
    </header>
    <section class="row">
        <div class="scroll-left"></div>
        <div class="row-scroll">
            {{for articles}}

                          // An if, else and some standard content insertion stuff was here

            {{/for}}
        </div>
        <div class="scroll-right"></div>
    </section>
    {{/for}}
</div>
```

**EDIT:** Forgot to mention, I am loading this from an external file using John Papa's code (http://msdn.microsoft.com/en-us/magazine/hh975379.aspx).

**Comment by BorisMoore** [comment]
Did you mean like this?:

```
{{for list ~outerData=#data}}
...
{{if ~outerData.some.path===...}}
...
```

See http://www.jsviews.com/#parentdata

**Comment by fconejero** [comment]
Hi, I'm having the same issue, but I'm guessing for a different reason since I don't have any if/else, or anything like that for that matter.

`<script id="addNovedadTemplate" type="text/x-jsrender">
        <div>
            <form class="form-inline" id="addNovedadForm">
                <div class="row">
                    <div class="form-group margin-top-10">
                        <label>Detalle</label>
                        <input type="text" id="novedadDetalleInput" class="form-control" name="Detalle" maxlength="500" value="" placeholder="Detalle de la novedad" required>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group margin-top-10">
                        <label>Autor</label>
                        <input type="text" id="novedadAutorInput" class="form-control" name="Autor" value="" placeholder="Autor de la novedad" required>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group margin-top-10">
                        <label>Sector</label>
                        <select class="col-md-9 form-control" id="sectorSelector" name="Sector" required>
                            <option value="">Seleccione ...</option>
                            {{for sectores}}
                            <option value="{{:Id}}">{{:Nombre}}</option>
                            {{/for}}
                        </select>
                    </div>
                </div>
            </form>
        </div>
        
    </script>`

**Comment by fconejero** [comment]
Hi, I'm having the same issue, but I don't think for the same reason, could you check it out?

```
<script id="addNovedadTemplate" type="text/x-jsrender">
        <div>
            <form class="form-inline" id="addNovedadForm">
                <div class="row">
                    <div class="form-group margin-top-10">
                        <label>Detalle</label>
                        <input type="text" id="novedadDetalleInput" class="form-control" name="Detalle" maxlength="500" value="" placeholder="Detalle de la novedad" required>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group margin-top-10">
                        <label>Autor</label>
                        <input type="text" id="novedadAutorInput" class="form-control" name="Autor" value="" placeholder="Autor de la novedad" required>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group margin-top-10">
                        <label>Sector</label>
                        <select class="col-md-9 form-control" id="sectorSelector" name="Sector" required>
                            <option value="">Seleccione ...</option>
                            {{for sectores}}
                            <option value="{{:Id}}">{{:Nombre}}</option>
                            {{/for}}
                        </select>
                    </div>
                </div>
            </form>
        </div>
        
    </script>
```
