### ISSUE TITLE
common js compliant lib

### ISSUE THREAD

**Issue by defunctzombie** [BorisMoore/jsrender#15]
I was wondering if it would be possible to make a common js compliant jsrender.js file (something that doesn't use window.views or whatnot outside of the main method).

I have a small wrapper I wrote around jsrender for nodejs:
https://github.com/shtylman/node-jsrender

and it would make bringing in jsrender code changes much easier :)

(If you accept patches for this I would be happy to provide one).

**Comment by Redsandro** [comment]
> I may not look more closely at AMD until JsViews and JsRender both get to Beta.

Any new developments on this?

**Comment by BorisMoore** [comment]
JsRender is now fully AMD and commonJs compliant - as is JsViews.

JsRender is available as a Node module. See https://www.npmjs.com/package/jsrender and https://github.com/BorisMoore/jsrender-node-starter
