### ISSUE TITLE
Feature Request - Switch / Case Statement.

### ISSUE THREAD

**Issue by blowsie** [BorisMoore/jsrender#152]
Im often writing templates where, if i was writing javascript I would be writing a Switch / Case statement.
http://www.w3schools.com/js/js_switch.asp

It would be nice if jsrender offered this functionality, for readability and possibly performance?

**Example of my template**
```
{{if ~getvar('renderType') == "email"}}
		code
{{else ~getvar('renderType') == "company"}}
		code
{{else ~getvar('renderType') == "file"}}
		code
{{else ~getvar('renderType') == "itemType"}}
		code
{{/if}}
```

**Suggested markup, updated to incorporate**  `{{break}}` (Thanks @coolbloke1324 ) 
```
{{switch ~getvar('renderType')}}
    {{case 'email'}}
    {{case 'email2'}}
        code
        {{break}}
    {{case 'file'}}
        code
        {{break}}
{{/switch}}
```

**Comment by BorisMoore** [comment]
Closing "After V1.0" issues for now - to reopen as appropriate.
