### ISSUE TITLE
Build options with multiple targets, including With/Without jQuery

### ISSUE THREAD

**Issue by jeffrose** [BorisMoore/jsrender#160]
While I understand that JsRender is the next generation of jQuery Templates, it does not actually need jQuery and could have broader usage without it. Have you considered breaking out the jQuery integration into an additional, optional file?

````
jsrender.js
jquery.jsrender.js
````

The current integration actually causes some confusion since the interface changes based on whether jQuery is present or not, i.e. `jsviews` vs. `$.views`.

**Comment by BorisMoore** [comment]
Closing "After V1.0" issues for now - to reopen as appropriate.
