### ISSUE TITLE
JSRender cannot work on Chrome Application and Extension

### ISSUE THREAD

**Issue by jeremychone** [BorisMoore/jsrender#164]
The upcoming Chrome App Model and extension do not support client side eval or even new Function, and therefore JSRender cannot compile the HTML. 

Any way to resolve this (beside pre-compilation)? 

Update: Apparently there are a workaround way to do it: http://developer.chrome.com/trunk/apps/sandboxingEval.html

Btw, I do not know the implementation implications, but it would be nice if JSRender pre-compilation would be to a data-structure rather than a function, this way, it won't need eval and new Function (that are so hated among Web people). Might be slower, but perhaps not that much.

**Comment by BorisMoore** [comment]
Closing "After V1.0" issues for now - to reopen as appropriate.
