### ISSUE TITLE
Removing tabs from template compilation markup

### ISSUE THREAD

**Issue by blowsie** [BorisMoore/jsrender#178]
I wanted to see what your opinions are on removing tabs (white space) from the templates when they are compiled. This would reduce the size of the javascript objects.

Considerations:
* Performance of using `.replace()`
* Could this break anything in the templates

The proposed change:

`function TmplObject(markup, options) {` - Line 603

```
tmpl = $extend(
				{
					markup: markup.replace(/\t/g, ''),
					tmpls: [],
					links: {},
					bnds: [],
					render: renderContent
				},
				options
			);
```

**Comment by BorisMoore** [comment]
Closing "After V1.0" issues for now - to reopen as appropriate.
