### ISSUE TITLE
ETA for release?

### ISSUE THREAD

**Issue by KaineVarley** [BorisMoore/jsrender#183]
Hi Boris,

Apologies for posting this as an issue, but there didn't seem to be any other way of contacting you other than via email.

I am using JsRender in one or two of my sites, and wondered if there was an ETA for release yet? It's a great product, but some of the powers that be get a little nervous using Beta software.

Cheers and thanks for your efforts.

Kaine

**Comment by BorisMoore** [comment]
Getting very close to V1.0 now. The last commit was a release candidate: https://github.com/BorisMoore/jsrender/commit/7facd628ff2b858c38e453edcd9613ff1d0246cc

**Comment by BorisMoore** [comment]
Closing, but putting under #251 - for notification of release
