### ISSUE TITLE
Error: view._hlp(...) is not a function. is hard to track down

### ISSUE THREAD

**Issue by pedz** [BorisMoore/jsrender#186]
Life is improving but I'm hoping it will keep getting better.

I see you have some TODOs in the code and you have some hooks which are not documented (to my knowledge).   I am often tempted to start writing documentation for jsrender (I don't use jsviews yet) but I know the code is in flux so keep waiting.  

I see you have $.views.settings with some debug options.  I can also tie into $.views._err but I fear that that might change.

The templates appear to have a debug option.  One suggestion is instead of this:

    		+ (tmplOptions.debug ? "debugger;" : "")

do

    		+ (tmplOptions.debug ? tmplOptions.debug : "")

Then the user can set debug = "debugger;" or another string of his choosing.

Eventually what I'd like is a general hook or perhaps two -- one for syntax errors and another for execution errors.  What I intend to do with those hooks is to have an empty tag with an id and then just append the errors to the tag.  It would be nice to be able to have the template name and what helper or tag is being used.  I assume line numbers is not possible.

**Comment by BorisMoore** [comment]
Closing "After V1.0" issues for now - to reopen as appropriate.
