### ISSUE TITLE
{{for Number}} support

### ISSUE THREAD

**Issue by Irrelon** [BorisMoore/jsrender#199]
Hey Boris,

I think I'm being a bit dense today so forgive me if I'm doing this wrong and there is an obvious way. I looked through the code and couldn't see it.

I want to loop using {{for}} and pass a number to loop x number of times like:

```
{{for 5}}
```

or if myVar = 5 :

```
{{for myVar}}
```

Is this currently possible? It doesn't seem to work for me at the moment! :)

**Comment by BorisMoore** [comment]
Closing "After V1.0" issues for now - to reopen as appropriate.
