### ISSUE TITLE
jsrender.min.js Props tag is not working

### ISSUE THREAD

**Issue by Edorka** [BorisMoore/jsrender#253]
I'm getting an "Error: Unknown tag: {{props}}. " exception when trying to apply object properties to another template. This error is happening when including jsrender.js from bower using "bower install jsrender"

**Comment by BorisMoore** [comment]
Maybe bower is not loading a recent version. You should look at which version it is loading. See https://github.com/BorisMoore/jsrender/issues/225. Full bower support is planned for V1.0. Can you  load jsrender directly? (http://www.jsviews.com/#download)

**Comment by Paul-Martin** [comment]
Yes.  The version pulled from bower is to an older commit.  Easiest to just use the following dependency:

"jsrender": "git://github.com/BorisMoore/jsrender#master"

This will pull from the head.

**Comment by Edorka** [comment]
We have recovered our previous copy but I thought it would be important to advice others.
Thanks for your great job.
