### ISSUE TITLE
busy indicator when big template on rendered

### ISSUE THREAD

**Issue by sheillendra** [BorisMoore/jsrender#259]
Hallo @BorisMoore , can you help me, I have tried using the promise (), setTimeout or jquery.when to display busy indicator before my big template is rendered, and after the rendering process is complete, the indicator will be closed, but my efforts remain unsuccessful. Indicator will appear along with the completion of the process of rendering

**Comment by BorisMoore** [comment]
Sorry, but that sounds like a question that is not actually dependent on JsRender. If would be the same no matter what process you are setting up the busy indicator to wait for. I can't answer general coding questions here... The JsRender issues list is only for JsRender-specific problems, bug reports or questions.

**Comment by sheillendra** [comment]
yes I understand, sorry, but it is very annoying when use jsrender. At function $.render [TEMPLATE_NAME] (params), could we add a callback as second params which will be executed before or after the rendering is complete?.

**Comment by BorisMoore** [comment]
But the rendering is synchronous. You don't need a callback.

var html = $.render.myTemplate(data, ...);
_**// Now the rendering is done. (Rendered to string)**_
$("#container").html(html);
_**// Now the rendered string is inserted in the DOM.**_

That's if you are using JsRender, not JsViews.

With JsViews it would be:
myTemplate.render("#container", data, ...);
_**// Now the rendered string is inserted in the DOM.**_

**Comment by sheillendra** [comment]
Could see my example at http://jsfiddle.net/sheillendra/7dLnmuq7/1/

when the "start" button is pressed, the text in the target element should be replaced with the word "busy .. rendering is begins" before rendering starts, but what happens is the text "busy .. rendering begin" will appear in conjunction with the completion of the rendering process.

I've been using setTimeout, Promise, deferred, when, but still can not indicators appear first.

**Comment by BorisMoore** [comment]
http://jsfiddle.net/7dLnmuq7/2/

**Comment by sheillendra** [comment]
wow, thank you very much @BorisMoore , it turns out there is something wrong on my setTimeout yesterday.
