### ISSUE TITLE
composition of templates or template of templates ?

### ISSUE THREAD

**Issue by yiakwy** [BorisMoore/jsrender#260]
For e.g, I have a series of templates, like t1, t2, t3...

I want to use them to generate a template by some hints like {order: ['t2', 't3', 't1'...]}

I learn JsRender API carefully but I didn't figure out an approach to it. 

Anyone can help me on this! Urgent!

If that is impossible for the current version, I would like to make pull request to enhance the api.

My current approach is using jquery to assemble templates. But My ideal approach is using lexical parser to parser it by using stacks where one is pointing to order list or some other hints to generate template automatically. 

Hence I would like "template of templates or generation" could also be the feature of JsRender. This will relieve the the awkward by using such engine while other ugly engine like php can easily resolve it.

**Comment by sheillendra** [comment]
use helpers to load nested template

**Comment by yiakwy** [comment]
Yes but nested tempalte could consist different components.

That means a variable template should be adopt. I resolve this by using
codes to trigger javascirpt to do resemlbe and return it as JsRender codes.

But I wish I could have such syntax:

for currContext tmpl=$currContext.tmpl

while

{tmpl:}

within the data define how should it be interpreted.

In short, I wish template engine can deduce from data how template is
generated not by programmer. Otherwise the code could be very ugly.

2015-06-16 20:01 GMT+08:00 suryana <notifications@github.com>:

**Comment by yiakwy** [comment]
Your solution doesn't resolve my qeustion because $.render(data, template, {heplers:...}) does not touch data. I wish there is a machinism that template will be dynamic according to data.

I want data has some dynamic hints where template can adapt itself according to these hints.

For example tmpl=#x where x should be a variable. However I have test this can not go through with JsRender.

**Comment by BorisMoore** [comment]
When you set the tmpl reference it can be either a static value - template name - or an expression which returns either a template name or even an actual compiled template.

For example: `{{include tmpl=nameOrExpr /}}` : http://www.jsviews.com/#includetag

http://www.jsviews.com/#samples/jsr/composition

Some of the samples use variables or expressions -  e.g. http://www.jsviews.com/#samples/jsr/composition/tmpl-objects `{{for languages tmpl=~columnTemplate/}}`

As to having template composition respond dynamically to data changes - JsViews is all that: about binding to 'observable' data and responding to changes: http://www.jsviews.com/#jsviews

For example this line https://github.com/BorisMoore/jsviews.com/blob/gh-pages/resources/tags/built-in-tags.js#L57 in the code for the tabs tag-control has the tmpl dynamically change based on user selection.

There are quite a few examples too in the unit tests:

e.g. https://github.com/BorisMoore/jsviews.com/blob/gh-pages/test/unit-tests/tests-jsviews.js#L1192, or https://github.com/BorisMoore/jsviews.com/blob/gh-pages/test/unit-tests/tests-jsviews.js#L8970 ...

**Comment by yiakwy** [comment]
@BorisMoore Thanks your response ^ ^!!!.  I initially did some experiments in the website repl inputting panel. But it seems that {{include tmpl=nameOrExpr}}, name can not be variable name indicated by data.

I will check all these materials carefully. Big Big thanks!!!

**Comment by yiakwy** [comment]
@I am inspecting your source for builtin tags for better understanding! Thanks for all you have done!

**Comment by BorisMoore** [comment]
I'll close this for now. `tmpl=someExpression` should work fine for returning different templates based on data. 

Let me know if you have further issues...
