### ISSUE TITLE
Rendering Nested Properties

### ISSUE THREAD

**Issue by madankn** [BorisMoore/jsrender#261]
Hi,

Is it possible to parse nested props? If yes can someone provide me an example or fiddle?

Thanks,
Madan KN

**Comment by BorisMoore** [comment]
You can access nested properties - i.e. properties of properties, using the simple syntax a.b.c - for example `{{:person.address.street}}` or `{{for person.phones}}...{{/for}}`. See for example http://www.jsviews.com/#assigntag, http://www.jsviews.com/#samples/jsr/paths
