### ISSUE TITLE
use in requirejs has error

### ISSUE THREAD

**Issue by benleilei** [BorisMoore/jsrender#262]
in Chrome 43.0.2357.124 m, it has a error: 

Uncaught TypeError: Cannot assign to read only property 'constructor' of #<Object>
compileTag @ jsrender.js:544
theStore @ jsrender.js:728
theStore @ jsrender.js:702
(anonymous function) @ jsrender.js:1347
(anonymous function) @ jsrender.js:1470

**Comment by BorisMoore** [comment]
Hello - sorry, I missed this earlier. 

My tests with require js are working correctly. Can you provide a jsfiddle showing the problem, or more information about your error scenario? I don't have any repro for the above error message - so I can't investigate further.

Thanks!

**Comment by BorisMoore** [comment]
Closing, since no feedback received...
