### ISSUE TITLE
Pulling in EventLocation from Array

### ISSUE THREAD

**Issue by vman92** [BorisMoore/jsrender#267]
I am a new developer and I am trying to figure out how to display EventLocation during a render. The Title appears to operate properly. But, for some reason I can't get EventLocation to display. Can I display a field value in my array using something like EventLocation_1? Right now I can display the Index value of the records I am displaying using - :#getIndex()

<script id="UpcomingEventsTemplate" type="text/x-jsrender">
	{{if dcn[0]._recordSet.length==0}}
		<div class="no-upcoming-events">
			<h3>There are no upcoming events to display</h3>
			<div id="NewItem"><a class="addnoevent" href="#">New Item</a></div> 
		</div>
	{{else}}	
		<div class="upcoming-events">
			<div class="list-events">
					{{for dcn[0]._recordSet ~dcn=dcn[0] ~dcn1=dcn[1] ~webAbsoluteUrl=_xData["webAbsoluteUrl"]}}
						<div class="event">
							<div class="event-date">
								<span class="event-month" title="{{getDateTime:EventDate}}">{{convertDateIn:EventDate dateFormat="datefmt_month"}}</span>
								<span class="event-day" title="{{getDateTime:EventDate}}">{{convertDateIn:EventDate dateFormat="datefmt_0date"}}</span>
							</div>
							<div class="event-info">
								{{if ~Permission.canEditListItems(~dcn1)}}
									<div id="EditItem" listItemId = "{{:ID}}" dcnIndex = "0"><span class="pencil"><a href="#"><i class="fa fa-pencil-square-o fa-2"></i></a></span></div>
								{{/if}}
									<h3 class="event-title"><span name="eventDetailLink" page="{{:~webAbsoluteUrl}}/Pages/Event-Detail.aspx" eventID ="{{:ID}}" eventDetailVMName="EventDetail" EventDetailStamp="{{convertDateIn:EventDate dateFormat='datefmt_eventStamp'}}">{{:Title}}</span></h3>
									<h3 class="event-title"><span name="eventDetailLink" page="{{:~webAbsoluteUrl}}/Pages/Event-Detail.aspx" eventID ="{{:ID}}" eventDetailVMName="EventDetail" EventDetailStamp="{{convertDateIn:EventDate dateFormat='datefmt_eventStamp'}}">{{:#getIndex()}}</span></h3>
										{{if ~areDatesEqual(EventDate, EndDate, false) == false}}
											<div>
												<span class="time" title="{{getDateTime:EventDate}}">Multi-Day Event</span>
											</div>
										{{else fAllDayEvent == true}}
											<div>
												<span class="time" title="{{getDateTime:EventDate}}">All Day Event</span>
											</div>
										{{else}}
											<div>
												<span class="time" title="{{getDateTime:EventDate}}">{{convertDateIn:EventDate dateFormat="datefmt_time"}}</span> - <span class="time" title="{{getDateTime:EndDate}}">{{convertDateIn:EndDate dateFormat="datefmt_time"}}</span>
											</div>
										{{/if}}				
							</div>
					{{if #getIndex() == (~dcn._recordSet.length - 1)}}
						<a class="viewallevent" href="Events.aspx">View All</a>
					{{/if}}
						</div>
					{{/for}}
					{{if ~Permission.canAddListItems(dcn[1])}}
						<div id="NewItem"><a class="addevent" href="#">New Item</a></div> 
					{{/if}}
				</div>
		</div>
	{{/if}}
</script>

**Comment by BorisMoore** [comment]
Your question isn't clear to me. Can you show me an example of the data, and what you want to render from it? Or create a jsfiddle example?

**Comment by vman92** [comment]
<div class="upcoming-events">
			<div class="list-events">
					{{for dcn[0]._recordSet ~dcn=dcn[0] ~dcn1=dcn[1] ~webAbsoluteUrl=_xData["webAbsoluteUrl"]}}
						<div class="event">
							<div class="event-date">
								<span class="event-month" title="{{getDateTime:EventDate}}">{{convertDateIn:EventDate dateFormat="datefmt_month"}}</span>
								<span class="event-day" title="{{getDateTime:EventDate}}">{{convertDateIn:EventDate dateFormat="datefmt_0date"}}</span>
							</div>
							<div class="event-info">
								{{if ~Permission.canEditListItems(~dcn1)}}
									<div id="EditItem" listItemId = "{{:ID}}" dcnIndex = "0"><span class="pencil"><a href="#"><i class="fa fa-pencil-square-o fa-2"></i></a></span></div>
								{{/if}}
									<h3 class="event-title"><span name="eventDetailLink" page="{{:~webAbsoluteUrl}}/Pages/Event-Detail.aspx" eventID ="{{:ID}}" eventDetailVMName="EventDetail" EventDetailStamp="{{convertDateIn:EventDate dateFormat='datefmt_eventStamp'}}">{{:Title}}</span></h3>
									<h3 class="event-title"><span name="eventDetailLink" page="{{:~webAbsoluteUrl}}/Pages/Event-Detail.aspx" eventID ="{{:ID}}" eventDetailVMName="EventDetail" EventDetailStamp="{{convertDateIn:EventDate dateFormat='datefmt_eventStamp'}}">{{:url}}</span></h3>
									<h3 class="event-title"><span name="eventDetailLink" page="{{:~webAbsoluteUrl}}/Pages/Event-Detail.aspx" eventID ="{{:ID}}" eventDetailVMName="EventDetail" EventDetailStamp="{{convertDateIn:EventDate dateFormat='datefmt_eventStamp'}}">{{>#index}}{{:Contact}}</span></h3>
									<h3>Testing Now!</h3>
																	
										{{if ~areDatesEqual(EventDate, EndDate, false) == false}}
											<div>
												<span class="time" title="{{getDateTime:EventDate}}">Multi-Day Event</span>
											</div>
										{{else fAllDayEvent == true}}
											<div>
												<span class="time" title="{{getDateTime:EventDate}}">All Day Event</span>
											</div>
										{{else}}
											<div>
												<span class="time" title="{{getDateTime:EventDate}}">{{convertDateIn:EventDate dateFormat="datefmt_time"}}</span> - <span class="time" title="{{getDateTime:EndDate}}">{{convertDateIn:EndDate dateFormat="datefmt_time"}}</span>
											</div>
										{{/if}}				
							</div>
					{{if #getIndex() == (~dcn._recordSet.length - 1)}}
						<a class="viewallevent" href="Events.aspx">View All</a>
					{{/if}}
						</div>
					{{/for}}
					{{if ~Permission.canAddListItems(dcn[1])}}
						<div id="NewItem"><a class="addevent" href="#">New Item</a></div> 
					{{/if}}
				</div>
		</div>

**Comment by BorisMoore** [comment]
I have no idea what EventLocation is, or what you want to do with it. You have shown your template, but EventLocation is not even in there...

Also this Issues database is for calling out bugs and missing functionality in JsRender, not for requesting help with your own apps. So I will need to close this unless you have a *really specific* simple question, and can make it *really obvious* with a jsfiddle example what your problem is...
