### ISSUE TITLE
Missing example for 03_tree-view_recursive-nested-each.html

### ISSUE THREAD

**Issue by sadfuzzy** [BorisMoore/jsrender#268]
Missing example for 03_tree-view_recursive-nested-each.html
It was very useful!

**Comment by BorisMoore** [comment]
Yes, it has been moved, some time back...

Many samples that were originally on the JsViews and JsRender GitHub demos folders have been updated and moved to http://www.jsviews.com/#samples.

The tree view ones are here: http://www.jsviews.com/#samples/tag-controls/tree

**Comment by BorisMoore** [comment]
Closing this issue. (@sadfuzzy: I didn't hear back from you - so I assume you picked this up...)
