### ISSUE TITLE
Parent index returns current index inside condition

### ISSUE THREAD

**Issue by agrinei** [BorisMoore/jsrender#270]
Consider the following json and template:

[{"description":"Element 1",
 "arrayProperty":[ {"itemId":"1.1","itemName":"Item 1.1"},
                   {"itemId":"1.2","itemName":"Item 1.2"},
                   {"itemId":"1.3","itemName":"Item 1.3"}]
},
{"description":"Element 2",
 "arrayProperty":[ {"itemId":"2.1","itemName":"Item 2.1"},
                   {"itemId":"2.2","itemName":"Item 2.2"},
                   {"itemId":"2.3","itemName":"Item 2.3"}]
}]

[script id="templateJsRender" type="text/x-jsrender"]

	{{:(#index)}} {{:description}}

	{{for arrayProperty}}
	
		[p]

			[span]{{:#parent.getIndex()}}[/span]
			- 
			{{if #index == 0}}
			[span]{{:#parent.getIndex()}}[/span]
			{{/if}}
			- 
			[span]{{:#parent.getIndex()}}[/span]

		[/p]
		
	{{/for}}

[/script]

The {{:#parent.getIndex()}} that is inside the {{if}} always shows 0 (zero). The other ones, outside the condition, return the correct value.

**Comment by agrinei** [comment]
Actually, #parent.getIndex() returns the current index (not the parent). In the case above it's 0 (zero).

**Comment by agrinei** [comment]
http://jsfiddle.net/6zLu7mmd/4/

**Comment by agrinei** [comment]
Just found this 
http://stackoverflow.com/questions/17747111/jsrender-cannot-access-parent-variable-inside-if-condition

**Comment by BorisMoore** [comment]
It looks like you ended up by understanding how the view hierarchy works, and the fact that our {{if}} test is itself adding a child view, so you need an extra level of parent.parent...

If not, let me know...

**Comment by agrinei** [comment]
Yes, now I understand! :-)
Thank you for taking your time to answer, and also for the awesome lib!


Best wishes,


Agrinei
