### ISSUE TITLE
Accessing parent data inside props tag

### ISSUE THREAD

**Issue by jmichaelterenin** [BorisMoore/jsrender#276]
I'm attempting to access parent data inside a props tag, and the only way that it works is if I'm using a function or helper. See below:

```
[%for services ~faddons=addons %]
    [%props accommodation ~svc=#data %]
        [%addons ~svc.id ~faddons ~svc.addons /%]  [%!-- Works --%]
        [%avail ~svc.available /%] [%!-- Works --%]
        [%for ~getFields(~svc.available)%] [%!-- Works --%]
            <option value="[%:#index+1%]">[%:#index+1%]</option>
        [%/for%]
        [%~svc.id%] [%!-- doesn't recognize it as a jsrender tag, outputs it as '[%~svc.id%]' --%]
    [%/props%]
[%/for%]
```

I'm using a different delimiter because it's inside a laravel blade template, which also uses double brackets.

**Comment by Paul-Martin** [comment]
Appears you might be missing either : or > depending on your encoding (or not) preference

[%:~svc.id%]

**Comment by jmichaelterenin** [comment]
Thank you very much, exactly the issue. Staring at this stuff for too long does that to me : )
