### ISSUE TITLE
Default npm Package version is 0.0.3

### ISSUE THREAD

**Issue by ianw89** [BorisMoore/jsrender#278]
Repo steps from clean project new to jsrender:
1. npm install jsrender
2. Be confused by most documented functionality being missing
3. Realize 0.0.3 is what was installed and bang head on table :-)

I get that 1.0.0-rc70 is technically a released package. should it just be released? Can you mark it as the latest package to get by default? Pretty confusing to get 0.0.3.

**Comment by BorisMoore** [comment]
That is strange. It looks like you are getting this https://github.com/defunctzombie/node-jsrender/blob/master/package.json - rather than this: https://github.com/BorisMoore/jsrender/releases

The jsrender name was originally associated with the https://github.com/defunctzombie/node-jsrender repo, and was subsequently moved to https://github.com/BorisMoore/jsrender. 

When I do a test install npm install jsrender does install the rc70 version, for me... Is there anything in your environment that could be pointing it to the earlier version?

**Comment by BorisMoore** [comment]
@ianw89 - Hi Ian, I don't have any repro of your issue. As mentioned above, it sounds like it must be something specific to your environment - or at least I hope so :). Can you confirm whether you are installing into an directory with no package.json, and that you have not in the past installed an earlier version of jsrender node module?

**Comment by BorisMoore** [comment]
I did finally get information from the npm support team - and the  explanation is apparently as follows:

> Current npm versions will, if you say "npm install jsrender" use the value of the latest tag and install v1.0.0-rc.70. By current versions, I mean npm@3.4.1 or later.

> https://github.com/npm/npm/blob/master/CHANGELOG.md#v341-2015-11-12
> Earlier npm versions would look for the first version that matched *, which is 0.0.3, due to prereleases not matching ranges.

So the fix will be to use version numbers like 0.9.71 rather than 1.0.0-rc.71.

I will switch to the 0.9.71 style from the next update onwards.

**Comment by ianw89** [comment]
Yeah, this makes sense. Prerelease tags should generally just be used for, well,
prereleases that most people wont adopt unless they are specifically trying to
(to try a new beta feature or whatever).

On Mon, Dec 7, 2015 at 9:21 PM, Boris Moore < notifications@github.com > wrote:
I did finally get information from the npm support team - and the explanation is
apparently as follows:

Current npm versions will, if you say "npm install jsrender" use the value of
the latest tag and install v1.0.0-rc.70. By current versions, I mean npm@3.4.1
or later.

https://github.com/npm/npm/ blob/master/CHANGELOG.md#v341- 2015-11-12
Earlier npm versions would look for the first version that matched *, which is
0.0.3, due to prereleases not matching ranges.

So the fix will be to use version numbers like 0.9.71 rather than 1.0.0-rc.71.

I will switch to the 0.9.71 style from the next update onwards.

**Comment by BorisMoore** [comment]
In fact they now consider the previous behavior (where prereleases where not installed) to be a bug (design bug if you will) and they have fixed it in the later npm.

**Comment by ianw89** [comment]
Cool.
