### ISSUE TITLE
Conflict with Liquid syntax

### ISSUE THREAD

**Issue by nasht00** [BorisMoore/jsrender#281]
My site is generated by Jekyll, which uses Liquid as a templating language. They also use `{{ }}` to print variables.

When typing
```
<script id="myTemplate" type="text/x-jsrender">
Name: {{:name}}
</script>
```

`{{:name}}` gets rendered as an empty string before jsrender can catch it.

What are my options?

**Comment by nasht00** [comment]
I found my workaround:

`{% raw %}{{:name}}{% endraw %}`

**Comment by BorisMoore** [comment]
Ok - but alternatively you can use choose different delimiters, such as `<%...%>` using `$.views.settings.delimiters("<%", "%>")`.

See: https://github.com/BorisMoore/jsrender/issues/258
