### ISSUE TITLE
npm auto-update on cdnjs

### ISSUE THREAD

**Issue by maruilian11** [BorisMoore/jsrender#285]
hi, we want to add your lib on https://cdnjs.com with npm auto-update, but due to the problem #278 we use git auto-update temporarily.
could you please tag us or open an issue on cdnjs when you fix the problem.
then we can change config to npm auto-update.
thank you very much!

https://github.com/cdnjs/cdnjs/issues/6350
https://github.com/cdnjs/cdnjs/pull/6499

**Comment by maruilian11** [comment]
i have sent the PR to add npm auto-update. thank you very much!
https://github.com/cdnjs/cdnjs/pull/6531

**Comment by BorisMoore** [comment]
Thank you for working in this!
