### ISSUE TITLE
Dynamic Template Imports ?

### ISSUE THREAD

**Issue by daslicht** [BorisMoore/jsrender#293]
Hi,
is there a way to solve something like this : 

```
{{include tmpl= {{:template}}  /}}
```

Or is there a template extend ?

Are custom tags meant for this usage ?

**Comment by daslicht** [comment]
Ok I found a solution myself: 
```
app.get('/', function (req, res) {

		var tmpl = jsrender.templates("./app/home/index.html")
		var html = tmpl.render();
		var context = { hello: "world", template: html};

        res.render('app/layout', context, function(err, html) {
            res.send(err ? jsrender.views.converters.html(err.message) : html); // HTML encode message
        });
});

```

```
I am the Layout, next line is an include: <br>
<hr>

<!-- {{include tmpl='./app/home/index.html' /}} <br> -->
{{:hello}}
{{>template}} <br>
<hr>
{{include tmpl='./app/_include/footer.html' /}}

```

Are there any downsides of this solution ?

**Comment by daslicht** [comment]
How could I use the variable '''{{:hello}}''' inside the included template ?

**Comment by daslicht** [comment]
is there a way to include a template with context ?

**Comment by BorisMoore** [comment]
`tmpl=anyExpression` - it does not have to be the statically-defined name or selector string...

http://www.jsviews.com/#samples/jsr/composition/tmpl-objects

http://stackoverflow.com/questions/35627356/dynamically-assigning-different-templates-based-on-data-using-helper-or-custom

**Comment by daslicht** [comment]
Thank you !
