### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated 

### ISSUE THREAD

**Issue by daslicht** [BorisMoore/jsrender#294]
On the client I have created an event delegate which listen if a user clicks a link:
```
$(document).on('click', 'a' , (e) => {
    e.preventDefault();    
    
    switch ( e.target.pathname ) {
        
        case '/': { 
            console.log('home') ;
            let client_bundle = `/bundle.js`;
            let detailTmpl = require(`./home/index.html`)($);
            let context = {
                hello: "Brave New",
                client_bundle
            };
            let html = detailTmpl.render(context);
            $("#content_container").html(html); //that the line which outputs that warning
...

        
```
Why do I get the following warning in the console?:
```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
```

**Comment by daslicht** [comment]
Related:
http://stackoverflow.com/questions/24639335/javascript-console-log-causes-error-synchronous-xmlhttprequest-on-the-main-thr

**Comment by daslicht** [comment]
So it is because I load my browserify bundle like this:

``` <script src={{:client_bundle}}></script> ```

**Comment by daslicht** [comment]
I am trying to have a browserify bundle for each 'page' separated and one shared bundle.
By now I troed to include it like this:

./home/index.html
```
{{:client_bundle}}
``` 
This works but I get that xhr warning

If I try to include it with jQuery , I get $ is not defined:
```
$.getScript({{:client_bundle}});
```

**Comment by daslicht** [comment]
This seams to work, I think when I am ready with this project I am prepaired to write a blog about my experience... :
```
                let s;
               $.getScript( '/bundle.js' )
                    .done(function( script, textStatus ) {
                        console.log( textStatus  );
                        s = script
                    })
                    .fail(function( jqxhr, settings, exception ) {
                        console.log(  jqxhr, settings, exception );
                    });
                
                    let detailTmpl = require(`./home/index.html`)($);
                
                    let context = {
                        hello: "Brave New",
                        s
                    };
```

./home/index.html
```
<script>
{{:client_bundle}}
</script>
```

**Comment by BorisMoore** [comment]
Is this issue a real one (if not can you close it)? 

You seem to have `<script src="/bundle.js"></script>` here https://github.com/daslicht/jsviews-includes/blob/master/app/layout.html#L18 - which should work fine.

Why would you write `{{:client_bundle}}`?

**Comment by daslicht** [comment]
><script src="/bundle.js"></script>
would only allow one bundle for all pages

>Why would you write {{:client_bundle}}?
Because I wanted to have a dynamic bundle for each page 

still not sure how to handle it , and I am confused how to include jquery just once.

**Comment by BorisMoore** [comment]
OK - yes you need to define what is a top-level page - which will need jQuery (if loaded separately) and the initial clientbundle (which may include jQuery) loaded immediately (through script tags, not getScript(). But then if you load other 'sub-pages' (partials) as in  a single page app - you can define distinct client bundles for them too (definitely not including jQuery) and load them async with getScript.

It all depends on your chosen architecture....
