### ISSUE TITLE
JsRender for Node.jS - Server side nesting templates

### ISSUE THREAD

**Issue by SeminAl** [BorisMoore/jsrender#296]
I'm trying to create two jsrender template files: layout.html and contactus.html. So when user request contactus.html (which is partial view) I would like to wrap it inside layout.html... 

Is this possible to accomplish with {{include tmpl=.../}} or I need to use some hacks...

This is like the first thing everybody needs to use when using JsRender on server side, and there is no any documentation about it...

**Comment by BorisMoore** [comment]
Did you find the documentation?

- http://www.jsviews.com/#node/filetmpls - see nested calls to file-based templates. 

Also 
- https://github.com/BorisMoore/jsrender-node-starter/blob/master/templates/layout-movies.html#L33
- https://github.com/BorisMoore/jsrender-node-starter/blob/master/templates/layout-movies.html#L38

and many others on the https://github.com/BorisMoore/jsrender-node-starter site.
