### ISSUE TITLE
How to use it on webpack

### ISSUE THREAD

**Issue by chan15** [BorisMoore/jsrender#297]
```
$(function() {
    let container = $('#container');
    let data = {name: 'chan'};
    let tmpl = $.templates('<div>{{:name}}</div>');
    let html = tmpl.render(data);

    container.append(html);
});
```

The is my code without webpack, it works, when I use webpack I load jsrender moudle like:

```
let jsrender = require('jsrender');
require("imports?this=>window!jsrender");

$(function() {
    let container = $('#container');
    let data = {name: 'chan'};
    let tmpl = $.templates('<div>{{:name}}</div>');
    let html = tmpl.render(data);

    container.append(html);
});
```

and I got `bundle.js:55 Uncaught TypeError: $.templates is not a function`, how to make it work?

jquery@1.12.3
jsrender@0.9.75

**Comment by BorisMoore** [comment]
You don't need to do `require("imports?this=>window!jsrender");` since you have already got the line `let jsrender = require('jsrender');`. The import loader is an alternative way of doing the same thing...

If jQuery is loaded globally (as a script file) then this will work:

```
require('jsrender');
$(function() {
    let container = $('#container');
    let data = {name: 'chan'};
    let tmpl = $.templates('<div>{{:name}}</div>');
    let html = tmpl.render(data);

    container.append(html);
});
```

because `require('jsrender');` will load JsRender and attach it to the global `$` (`window.jQuery`) as a plugin.

But if you are loading jQuery as a module, with webpack, then `window.jQuery` is not defined. You need to pass your local copy of jQuery to JsRender, by writing `require('jsrender')($);`. So you can do it like this:

```
let $ = require('jquery');
let jsrender = require('jsrender')($);
$(function() {
    let container = $('#container');
    let data = {name: 'chan'};
    let tmpl = $.templates('<div>{{:name}}</div>');
    let html = tmpl.render(data);

    container.append(html);
});
```

See the Browserify documentation: http://www.jsviews.com/#node/browserify@clientscript

**Comment by chan15** [comment]
I tried `require('jsrender');` alone too, still not work, and I load jQuery by webpack.config.js like:

```js
var webpack = require('webpack');

module.exports = {
    entry: './entry.js',
    output: {
        path: __dirname + '/assets/js/build',
        filename: 'bundle.js'
    },
    plugins: [
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery"
        }),
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                warnings: false
            }
        })
    ],
    module: {
        loaders: [
            {test: /\.js$/, exclude: /node_modules/, loader: "babel", query: {presets: ['es2015']}}
        ],
    },
};
```

therefore the jQuery is auto loaded everytime, but still get the error message

**Comment by BorisMoore** [comment]
But did you pass $ as a parameter? 

You need to get a reference to `$` and pass it as a parameter.

`require('jsrender')($);`

**Comment by BorisMoore** [comment]
If you use the correct syntax shown above, with the $ passed as parameter, this will work correctly. Closing this issue for now.

Also, there will be additional documentation on using webpack, in the next update.

**Comment by BorisMoore** [comment]
There is now a topic on webpack: http://www.jsviews.com/#node/webpack

**Comment by adriancmiranda** [comment]
@BorisMoore How can i require(from webpack) imagens on html views?
I try put in the jsrender.views.helpers, but, without success yet.

**Comment by BorisMoore** [comment]
I don't know how to do that. One way might be to write a  special loader: 'jsrender-loader'. 

Another might be to add a build step which writes the rendered template to file (as an html file) then use the html-loader to load that file - at which point the html-loader will be able to do its usual magic of 'requiring' the images, using the usual regex test for .png, .jpg etc. and using whatever loaders or rules you have set up for those paths...

I have not used webpack enough to help much more at this point. But if you do make progress on solving the scenario, I would be very interested to hear, and I could potentially then provide more documentation on jsviews.com based on the results... Let me know...

**Comment by dbauszus-glx** [comment]
Should it be possible to use jsrender in webpack without jQuery?

I currently load jsrender from my public js files like so:

`<script type="application/javascript" src="js/jsrender.js"></script>`

And then call the methods in my webpack modules from the window:

`window.jsrender.templates(xhr.responseText).render()`

This works well.

What I would like to do is to require jsrender from the node_modules which I use in the backend.

```
const jsr = require('jsrender');
jsr.templates(xhr.responseText).render()
```

I also tried to just require the jsrender-src from my public directory in the hope that this would bind jsrender to the window object, but this did not work.

`require('./jsrender-src');`

**Comment by dbauszus-glx** [comment]
I fussed it out...

`const jsr = require('jsrender')();`

Without the empty brackets the module did not execute with Webpack3.

![image](https://user-images.githubusercontent.com/22201617/30586740-d8c1cdac-9d28-11e7-8249-2015bc950277.png)

Compared with:

![image](https://user-images.githubusercontent.com/22201617/30586697-bb8a6f1e-9d28-11e7-961a-522ad349fc50.png)

And thereafter I am good to use

`document.querySelector('.myTmplContainer').innerHTML = jsr.templates(myTmpl).render();`

It might be worth ammending the [documentation ](http://www.jsviews.com/#node/webpack@jsrender)as this example did not work with Webpack3.

> If using JsRender without jQuery, or with jQuery loaded globally (as a script tag) this is done by calling:
> 
> var $ = require('jsrender'); // Without jQuery, or if jQuery is loaded globally

**Comment by BorisMoore** [comment]
I just returned from 3 weeks travelling. Sorry not to be able to  reply until now. 

Yes, you are correct. It is actually a documentation error, which I will fix soon. In fact to use webpack to load JsRender without jQuery, you do indeed need to use the syntax: 

var jsr = require('jsrender')();
var myTmpl = jsr.templates(...);
var html = myTmpl.render(myData);
...

Thanks for investigating!

**Comment by BorisMoore** [comment]
Documentation has been updated in commit 89.
