### ISSUE TITLE
Jsrender can not render table

### ISSUE THREAD

**Issue by hunters1094** [BorisMoore/jsrender#299]
Hi Boris

I'm using jsrender version v0.9.75 (Beta) and get a stranger situation.

I have a template like that: 

    {{for pageSummaries}}
      <tr>            
        <section class="panel">
          <h4 class="panel-title"><a href={{:link}}>{{:title}}</a></h4>
          <p> {{:content}}</p>
          <em class="meta">
            <span>                            
              Creater {{:creator}}, modifier {{:modifier}}, date {{:modified}}
            </span>
          </em>                
        </section>
      </tr>
    {{/for}}

when i remove the tr tag, it runs ok. But in it template, it renders the tr with empty data.

Don't know why. Thanks.

**Comment by BorisMoore** [comment]
A `<tr>` has to be inside a `<tbody>` and should only have `<td>` elements as children. Your HTML with a `<section>` as child of a `<tr>` is not valid HTML.

**Comment by hunters1094** [comment]
yes, thanks.
