### ISSUE TITLE
Provide a tool for pre-compiling templates

### ISSUE THREAD

**Issue by rosenfeld** [BorisMoore/jsrender#30]
Is it possible to make a tool available for precompiling templates (using node, for instance)?

This could be integrated in an assets builder setup or using tools like Guard.

I'm hoping this could improve performance under production.

Thanks for considering the idea.

**Comment by BorisMoore** [comment]
Browserify transform and {{clientTemplate}} support and full Node JsRender support are now available. 

JsRender is now available natively as a Node module.

See https://www.npmjs.com/package/jsrender and https://github.com/BorisMoore/jsrender-node-starter
