### ISSUE TITLE
"Unknown template" error slightly broken with jQuery 3.0+

### ISSUE THREAD

**Issue by brobison75** [BorisMoore/jsrender#305]
jsrender.js line 2151 (v0.9.82 web version):

        var tmplElem = this.jquery && (this[0] || error('Unknown template: "' + this.selector + '"')),

[.selector has been removed as of jQuery 3.0](https://jquery.com/upgrade-guide/3.0/#breaking-change-deprecated-context-and-selector-properties-removed).  Test with "$('#nonexistent_tmpl').render();" using jQuery 3.0+.  Console message under Chrome:

Uncaught JsViewsError {name: "JsRender Error", message: "Unknown template: "undefined""}

Obviously this is a minor issue, but worth pointing out.

**Comment by BorisMoore** [comment]
Yes, thanks for calling this out! I'll fix it in the next update.

**Comment by BorisMoore** [comment]
This has been fixed in commit v0.9.83
