### ISSUE TITLE
node and browser

### ISSUE THREAD

**Issue by puppetmaster3** [BorisMoore/jsrender#308]
(This may be my favorite project - I plan to use it 2 places at least.)
I have node working w/ file template and browser working w/ string template, very nice.

To make it great, in browser I will fetch() the template from the server, then render. So I can share the same template 'in-real-time'/reuse. I see you re-use via build step, I prefer 'fetch()' approach. The only reason I'm posting here is to see if you have something like the fetch approach?

If not, I will get it to work and publish article on how.
(separate I plan to do AMP this way, and publish that as well)

**Comment by cekvenich** [comment]
view-source:https://www.masons-foundation.org/post/amp/

It works great as such! thx again for this project.

**Comment by BorisMoore** [comment]
Good.

BTW there are a couple of places on jsviews.com which show async fetching of templates:

http://www.jsviews.com/#compiletmpl
http://www.jsviews.com/#samples/jsr/composition/remote-tmpl

But an additional goal addressed here: http://www.jsviews.com/#node/server-browser and in samples here: https://github.com/BorisMoore/jsrender-node-starter is to do initial rendering on the server with the same template. so there is no 'flicker' if the same template is then rendered in the browser. Also this allows the browser to then use data-linking (JsViews) and have client-side interactivity, with items being added and removed from dynamic lists, for example, without having to re-fetch the updated content, or even re-render the whole page in the browser. Just smart incremental rendering.

I haven't looked at the AMP proposals. The declared target is static pages, but it may be possible (and even more powerful and performant) to combine AMP optimisations with JsViews dynamic data=driven view interactivity in the browser...

Keep my posted with your findings, if you can. Thanks...

**Comment by cekvenich** [comment]
Hi Boris.
I will keep you posted. Works great front end and server side: 100% 
reuse. I plan to write an article, I will let you know.

And I have a meetup in Feb in NYC, one topic will be jsRender. If you 
can post that someplace please, for people to RSVP here. It is free, 
open source, no products will be pitched.

Also, do you have private email plz?

Cheers,
Vic
(vicmasons (at) gmail.com)

**Comment by BorisMoore** [comment]
Hi Vic,
Sure, I'll reply via email, so you'll have my email.

Boris
