### ISSUE TITLE
Requiring and using jsrender/jsviews with require.js

### ISSUE THREAD

**Issue by AndreaM16** [BorisMoore/jsrender#309]
I inherited a big javascript project made with javascript vanilla, jquery and [jsviews/jsrender][1]. Since it is made by few files of over 4000 lines of code each and I'm used to work with AngularJS, I'm trying to *modularize* it using [requirejs][2].

I'm having a weird problem on jsrender/jsviews initialization

> Uncaught TypeError: Cannot read property 'allowCode' of undefined

In **global.js**, given by

    define(['jquery', 'jsrender'], function($, jsrender){

      jsrender.settings.allowCode(true);

    });

Before trying to set up require, it used to work and be initialized like

    $.views.allowCode(true);

where `$.views` was an object with `settings` attribute.

I also tried

    $.jsrender.settings.allowCode(true);

but I get the same error.

If I do `console.log(jsrender);` I get `function (a,b){return new n.fn.init(a,b)}`

This is my **index.html**

    <script data-main="js/common" src="js/vendors/requirejs/require.js"></script>
    <script>
      require(['common'], function () {
         require(['global'])
      });
    </script>

And this is **common.js**

    requirejs.config({
        baseUrl : "js",
        paths : {
            jquery   : "vendors/...",
            jsrender : "vendors/..."
        }
    });

Even tho I haven't any configuration problems, this is project's structure

    |
    |-- index.html
    |-- js
    |     -- vendors
    |                -- jquery
    |                -- jsrender
    |     -- global.js
    |     -- common.js

**What causes this issue? How can I fix this?**

Thanks in advance.

  [1]: https://www.jsviews.com/
  [2]: http://requirejs.org/

**Comment by BorisMoore** [comment]
The two parameters: `jsrender` and `$` are in fact both the jQuery object. (Your console.log is showing it in minified form), So you can simply write:

    define(['jquery', 'jsrender'], function($){
      $.views.settings.allowCode(true);
      ...
    });

The effect of requiring `'jsrender'` as a dependency is that JsRender is loaded as a jQuery  plugin, so the `$` object includes the corresponding methods and objects, such as `$.views` and `$.render`.

**Comment by AndreaM16** [comment]
Hi Boris, thank you for your reply. When I'll be back at work I'll try and let you know. Have a good weekend.

**Comment by AndreaM16** [comment]
Hi Boris, I tried what you said `$.views.settings.allowCode(true);` but I still get `Cannot read property 'settings' of undefined`. I think this is cause by the fact that the developer who gave me the project imported scripts with `defer` attribute <script type="application/javascript" defer src="...">. Do you know any way to say to require to defer them?

**Comment by BorisMoore** [comment]
If you debug your code, you should be able to see (with a break point) what your $ and jsrender objects are. Are they the same ($===jsrender). Do they have a $.views or jrender.views object? Has JsRender been loaded. (Look at Network).

Here is a working sample:

[requirejs.zip](https://github.com/BorisMoore/jsrender/files/761493/requirejs.zip)

BTW you can try either alternative in global.js:

```
define(['jquery', 'jsrender'], function($, jsrender){
	$.views.settings.allowCode(true);
	...
});
```
```
define(['jquery'], function($) {
	require(['jsrender'], function($jsr) {
		$.views.settings.allowcode(true);
		...
	});
});
```

On defer: 'defer' is for loading using script tags. RequireJs being a script loader, will let you defer to when you call require(). You decide when that is in relation to document load.

**Comment by AndreaM16** [comment]
Hi Boris, I managed to solve using:

```
define(['jquery'], function($) {
	require(['jsrender'], function($jsr) {
		$.views.settings.allowcode(true);
		...
	});
});
```
Essentially, `$==jsrender` returned `false` because somehow `$` was not yet set up.

thanks for your answer.
