### ISSUE TITLE
`if` seems to discard data context

### ISSUE THREAD

**Issue by AndrewRevinsky** [BorisMoore/jsrender#314]
Boris, hi!

Again, `if` directive seems to discard data context. It happens in my setup describe below.

I have a pretty complex data object I pass to the template's `render()`. Part of it looks like this: 
<img width="322" alt="screen shot 2017-03-12 at 23 01 01" src="https://cloud.githubusercontent.com/assets/932990/23835420/025e52d0-0778-11e7-83fc-48c1913dcdd7.png">

So, if I use template like so:
```html
                  {{if isPresent_ddlCountries }}
                  <div class="form-group row no-gutters">
                    <label for="ddlCountries" class="p-1 col-12 col-md-5 col-lg-4 col-form-label col-form-label-sm text-md-right">Country:</label>
                    <div class="col-12 col-md-7 col-lg-8">
                      {{: tagOpen('#ddlCountries', 'class="form-control" ') }}{{: tagBody('#ddlCountries') }}
                    </div>
                  </div>
                  {{/if}}
```
.. I eventually receive an error:
```
TypeError: Cannot read property 'tagOpen' of undefined
```

VM's code:
![image](https://cloud.githubusercontent.com/assets/932990/23835440/96893fd8-0778-11e7-80e6-de9deaf74184.png)

Higher up the stack:
![image](https://cloud.githubusercontent.com/assets/932990/23835568/b1af7b2c-077a-11e7-8fbf-2866ea7da57a.png)

Thus, I have to use a sort of a hack, like so:
```
                  {{if isPresent('#ddlCountries') }}
                  <div class="form-group row no-gutters">
                    <label for="ddlCountries" class="p-1 col-12 col-md-5 col-lg-4 col-form-label col-form-label-sm text-md-right">Country:</label>
                    <div class="col-12 col-md-7 col-lg-8">
                      {{/if}}{{: tagOpen('#ddlCountries', 'class="form-control" ') }}{{: tagBody('#ddlCountries') }}{{if isPresent('#ddlCountries') }}
                    </div>
                  </div>{{/if}}
```
Note how I close the `if` just before inserting any other prop from the data object. I really find this bug-prone and am thinking I could be overlooking something.

Thoughts? Am I misusing the `if` directive? Or do I have to pass the data on somehow? Or is it actually a bug? Please advise.

I am using a minified latest version: 0.9.84.

**Comment by BorisMoore** [comment]
Hi Andrew - can you create a minimalist jsfiddle to show the issue?

**Comment by AndrewRevinsky** [comment]
It is very strange. As I started creating a Fiddle, problem seems to vanish. First, I couldn't repro it there, then, in my code.
The issue was real, the screenshots don't lie (generally). 

Anyway, here is the fiddle: https://jsfiddle.net/andrevinsky/h6g1bLbb/ - for reference. And it is working now.

**Comment by BorisMoore** [comment]
It really looks like you were not passing in the data object to the render method. It shows data as undefined in the trace above.

BTW in your jsfiddle you have `var tpl = $.template(tplText);` - it should be `$.templates`.

Of course you could have written more simply: 

```
var tpl = $.templates("#tpl");
var html = tpl.render(data);

```

**Comment by BorisMoore** [comment]
Closing this. Seems like it was not an actual issue...
