### ISSUE TITLE
How to use 'contentCtx' in jsRender without jsViews

### ISSUE THREAD

**Issue by Dineshkanin** [BorisMoore/jsrender#315]

**Comment by BorisMoore** [comment]
I will be adding a few documentation topics soon for creating custom tags, both in JsRender and JsViews, including 'contentCtx'.

Meantime, there are several unit tests available showing examples of its use:

https://github.com/BorisMoore/jsrender/blob/master/test/unit-tests/tests-jsrender-no-jquery.js#L2162-L2264

**Comment by BorisMoore** [comment]
Documention was added for this some time back. http://www.jsviews.com/#tagsapi@contentctx.  (See "Specifying data context within tag content: the contentCtx option")
