### ISSUE TITLE
accesing parent element in range

### ISSUE THREAD

**Issue by airsakarya** [BorisMoore/jsrender#316]
The range extending which Boris Moore shared [here](http://www.jsviews.com/#samples/jsr/tags/extend-for) is useful for most situtations. I am using "integer range" and works well.

Example
```
{{range start=1 end=10}}
//somethings
{{/range}}
```

Its not iteration of an array. Because of this, I can't reach its parent element with [these ways](http://borismoore.github.io/jsrender/demos/step-by-step/11_accessing-parent-data.html).

I'm not looping objects. Its needed to be and object to get parent element.

Is there any way to get parent element in a integer range loop?

**Comment by BorisMoore** [comment]
The methods here http://www.jsviews.com/#parentdata and here http://borismoore.github.io/jsrender/demos/step-by-step/11_accessing-parent-data.html
both work fine. It does not need to be looping objects. The `#parent` gets the parent view, not the parent of the data. For example:

```
{{range start=1 end=10 ~outerData=#data}}
      {{:#parent.parent.data.someProperty}}
      {{:~outerData.someProperty}}
{{/range}}
```  

Specifically, say...:

```
{{range start=1 end=10 ~outerData=#data}}
      {{:#parent.parent.data.start}}
      {{:~outerData.end}}
{{/range}}
```

**Comment by airsakarya** [comment]
Thanks for answer. I just trying to understand jsrender at all. I don't know what difference but both example now working now. OuterData example is simple for nested arrays.

Sometimes need to take a break and don't think about the code.
