### ISSUE TITLE
Whats the difference with handlebars?

### ISSUE THREAD

**Issue by AlexByte** [BorisMoore/jsrender#322]

**Comment by BorisMoore** [comment]
Basically JsRender functionality is a superset of Handlebars functionality. It is more flexible and powerful in its support/treatment of expressions in templates.  (And at the same time it is secure against using templates to create side effects or to inappropriately access globals). 

From a point of view of performance, it is similar to Handlebars for rendering templates, and faster for compiling templates.

The Mustache-inspired template syntax is similar, thought JsRender syntax is slightly more flexible and complete. 

I cannot currently provide a more detailed comparison and study of detailed differences or equivalences, but hope to do so at some point, after publishing the official  JsRender and JsViews V1.0 (which is currently my priority).

**Comment by BorisMoore** [comment]
Closing this issue...
