### ISSUE TITLE
Override default converter ":" ">"

### ISSUE THREAD

**Issue by Dineshkanin** [BorisMoore/jsrender#327]
How to override default converters in jsrender.

**Comment by BorisMoore** [comment]
'm travelling at the moment so can't reply until after returning on the 20th

**Comment by BorisMoore** [comment]
The built-in converters are
- `{{html:...}}` or `{{>...}}`
- `{{attr:...}}`
- `{{url:...}}`

http://www.jsviews.com/#convertersapi@html

You should be able to override them by declaring your own, as in:

```
$.views.converters("html", myConverterFunction);
$.views.converters("attr", myConverterFunction);
$.views.converters("url", myConverterFunction);
```

However the first one   does not work with the current implementation. I'll fix it in the next update. As a  temporary workaround (which will no longer work after the fix) you can instead write:

`$.views.sub._html =  myConverterFunction;`

**Comment by BorisMoore** [comment]
This has been fixed in commit 89
