### ISSUE TITLE
access iteration index

### ISSUE THREAD

**Issue by cyburk** [BorisMoore/jsrender#33]
it would be nice to have access from within a template to the current iteration index, e.g. {{=$ctx.index}}

some use cases:
- output a numbered data list
- limit to the top 10
- enable pagination for data tables (only show entries from 1-3, 4-6, etc.)

the index could always be stored in the data before hand, but there should not be a correlation between display position and data, e.g. a filtered data table, whose first result may not be the first data entry.

**Comment by trifolius** [comment]
hey @BorisMoore  have a range o for but decreasing...
for example 

 "{^{range members ^start=10 ^end=1}}"+
                "{^{:#index}}"+
"{{/range}}"+

**Comment by BorisMoore** [comment]
@trifolius: Hi. What is your question?

**Comment by BorisMoore** [comment]
You should be able to create a custom tag to do that. You can use a combination of the approach used for the {{sort}} example, here: http://www.jsviews.com/#samples/jsr/tags/wrap-content and here: http://www.jsviews.com/#samples/jsr/helpers
and the range tag shown here: http://www.jsviews.com/#samples/jsr/tags/extend-for and here: http://www.jsviews.com/#samples/tag-controls/range
