### ISSUE TITLE
silly doubt

### ISSUE THREAD

**Issue by suriyaJaay** [BorisMoore/jsrender#331]
will it support Angular 2?
if possible could u pls post example in Typescript along with remote json via jquery ajax?

Thanks alot

**Comment by BorisMoore** [comment]
There should not be any conflict between JsRender and Angular 2.

I don't work with Angular myself, nor with Typescript. You should be able to use the many JavaScript examples. If you need to convert to Typescript, you'll need to that yourself. 

I have not yet created typescript type definitions for JsRender (https://github.com/BorisMoore/jsrender/issues/211) but this may help: https://www.nuget.org/packages/jsrender.TypeScript.DefinitelyTyped/0.1.6

**Comment by BorisMoore** [comment]
Closing.
