### ISSUE TITLE
Can't call another root object on loop "for"

### ISSUE THREAD

**Issue by isatrio** [BorisMoore/jsrender#332]
The object look like below
```
{
audio: {
datas:[{name: "test"}, {name: "test 2"}]
url: 'http://someurl.com'
}
```

The template look like below
```
<script id="audioTemplate" type="text/x-jsrender">
  {{for audios.datas}}
    {{:name}}
    {{:audios.url}}
  {{/for}}
</script>
```

The audios.url can't show in the loop, the error is like "Uncaught TypeError: Cannot read property 'url' of undefined". Do you have suggestion for doing this?

**Comment by Paul-Martin** [comment]
url is a property of audio, whereas the context in the loop is audio.datas.
Try

```
{{for audios}}
  {{for datas}}
    {{:name}}
  {{/for}}
  {{:url}}
{{/for}}
```

**Comment by BorisMoore** [comment]
Paul's approach is fine as long as you don't need to mix the two levels - as in:

```
name
url
name
```

If you do, then take a look at [Accessing parent data](http://www.jsviews.com/#parentdata) for alternatives, such as:

```
{{for audio.datas ~url=url}}
  {{:name}}
  {{:~url}}
  {{:name}}
{{/for}}
```

**Comment by BorisMoore** [comment]
Closing this - since the question is answered.
