### ISSUE TITLE
How to access iterator in range

### ISSUE THREAD

**Issue by kiebor** [BorisMoore/jsrender#338]
I have a data structure like this:
```
{
someNumber: 5,
someStuff:[ ... ... ]
}
```

I can create a row of items conditionally based on the value of `someNumber` by repeating the below snippet 5x (and manually setting i from 1 to 5)

```
     {{ if someNumber >= i }}
           <span>true</span>
     {{ else }}
           <span>false</span>
      {{ /if }}
```

Ideally I would like to use range for simplicity. Something like:

```
{{ range start=1 end=5 }}
     {{ if someNumber >= [iterator] }}
           <span>true</span>
     {{ else }}
           <span>false</span>
      {{ /if }}
{{ /range }}
```
I can't find the in loop variable to expose the iterator/index of the current iteration. I have tried #index and #data but both resolve as null/undefined in the loop. I also noticed that `someNumber` is less than 0 when using the construct.

Can you point me at some documentation that explains how to do this (jsviews.com isn't quite clear nor does it explain validating in loop), or offer some advice.

Thanks.

**Comment by BorisMoore** [comment]
You can access the iterator from within nested blocks using [#getIndex()](http://jsviews.com/#viewobject@getindex). See also http://jsviews.com/#views@itemview (and the rest of that documentation topic).

In the next update you will be able to do

```
{{for someStuff start=1 end=5}}
   <span>true</span>
{{/for}}
```

but it looks as if you need something like:

```
{{for someStuff}}
  {{if #getIndex() < 6}}
    <span>true</span>
  {else}}
    <span>false</span>
  {{/if}}
{{/for}}
```

**Comment by kiebor** [comment]
Thanks, Boris. Below works for me to get the iterator in the range/for loop

```
{{range start=1 end=5}}
  {{if #getIndex() < 4 }}
    <span>true</span>
  {{/if}}
{{/range}}
```
but what I wanted was to be able to validate the iterator against `someNumber`. In this loop my data value `someNumber` equates to null, or is inaccessible.

Ideally I was hoping to achieve something like:
```js
for (i = 1; i < 6; i++) {
  if(someNumber > i){
     //true
  }
}
```

**Comment by BorisMoore** [comment]
Not sure why you put `~Average` - (with a `~`). Is it in the data or is it a helper? You don't show your  data or JSON so I have no idea where Average is defined. I suppose it is higher up in the data object graph, in which case you need to read this:  [Accessing parent data](http://jsviews.com/#parentdata)
