### ISSUE TITLE
<template> instead of <script>

### ISSUE THREAD

**Issue by sp00n** [BorisMoore/jsrender#345]
Is there a way to use a `<template>` tag instead having to use `<script>`? The tag has been around since 2013, and [browser support](https://caniuse.com/#feat=template) seems to be pretty good now.
In the [documentation](https://www.jsviews.com/#d.templates) it says that it's possible "_to declare a template in a non-script element_", although discouraged, because it could cause images to load incorrectly. For `<template>` tags this should avtually be a non issue, because its content is not rendered on page load anyway.

However when I try to use such a template with e.g. `let myTmpl = $.templates("#template-tag-id");`, I receive the following error:
`JsRender Error: #template-tag-id: Use script block, not TEMPLATE`

There's a specific element check in jsrender.js, line 1112 that triggers this error:
```javascript
if (elem.tagName !== "SCRIPT") {
	error(value + ": Use script block, not " + elem.tagName);
}
```

**Comment by BorisMoore** [comment]
A `<template>` tag does not render but its contents are supposed to be valid HTML markup, and are parsed and validated by the browser. That means that for both `<template>` and `<div>` tags, the browser may modify the contents (to try to make valid HTML), and so when the jsrender code calls `innerHTML` to get the template string, the result may be quite incorrect.

Try commenting out the  line 1112 in jsrender.js, and use the following template:

```
<someElement ...>
<br/>
{{>myHTMLstring}}
</somelement>
```
Only `<script ...>` works correctly... The others transform the innerHTML to

```
<br>
{{&gt;myHTMLstring}}
```

**Comment by sp00n** [comment]
Yeah, I stumbled across the {{>varName}} as well and wondered why it wouldn't parse the data correctly. Bummer.

**Comment by BorisMoore** [comment]
It will also fail in many other cases which are not valid HTML. Text is not allowed between tr and td, or ul and li, etc. so `<tr>{{for items}}<td>...` is not valid. Not to mention things like `{{if foo}}<div class="a">{{else}}<div class="b">{{/if}}`, etc. etc.
