### ISSUE TITLE
Prevent loading resource in template

### ISSUE THREAD

**Issue by Jogai** [BorisMoore/jsrender#347]
When I have a template in my html like this: 

    <script type="text/x-jsrender" id="photoTemplate">
        <figure>
            <img src="/PhotoPath/{{: Name}}?preset=AlbumCoverThumb" alt="{{: Description }}" class="img-responsive img-thumbnail" />
            <figcaption>{{: Name}}</figcaption>
        </figure>
    </script>

There is always a request going to something like /PhotoPath/%7B%7B:%20Name%7D%7D 

Is there something I can do to prevent this from happening?

**Comment by BorisMoore** [comment]
That should not happen. It works for me. If you can't figure it out, create a jsfiddle showing the issue.

**Comment by Jogai** [comment]
Sorry, you're right. I'm using another component which depends on jsrender so I should check better where the issue originates.

My test case for the interested: https://codepen.io/jogai/pen/NJYrZB
