### ISSUE TITLE
renderFile to accept a file as input

### ISSUE THREAD

**Issue by dbauszus-glx** [BorisMoore/jsrender#353]
I am having a problem with relative paths not being supported by my cloud provider. I can get the file alright with fs.readFileSync but I cannot use the './' path syntax. While probably not possible in the short run is there any way to provide a file for the renderFile method?

**Comment by BorisMoore** [comment]
In fact `renderFile()` does accept absolute paths as well as relative ones. For example if you take a look at [this line](https://github.com/BorisMoore/jsrender-node-starter/blob/master/index-express.js#L67) of the [jsrender-node-starter](https://github.com/BorisMoore/jsrender-node-starter) sample app. 

You can replace 

```js
var html = jsrender.renderFile('./templates/layout-hello.html', { hello: "world" });
```

by

```js
var html = jsrender.renderFile(process.cwd() + '/templates/layout-hello.html', { hello: "world" });
```
or, you can do:

```js
var dn = __dirname;

app.get('/hello/world', function(req, res) {
  var html = jsrender.renderFile(dn + '/templates/layout-hello.html', { hello: "world" });
  ...
};
```

All three will work in the same way - and the second and third are using absolute paths.

If you really need to get the file first, from `readFileSync(filePath, encoding)` then you can take the returned string, (which is the markup for your template), and compile it as a template and render it against data as follows:

```js
var markup = Fs.readFileSync(filePath, "utf8");
var tmpl = jsrender.templates(markup);
var html = tmpl.render({ hello: "world" });
```

**Comment by BorisMoore** [comment]
I didn't hear back on this. Closing for now.
