### ISSUE TITLE
any breaking changes between 0.9.82 and current 1.0.5 ?

### ISSUE THREAD

**Issue by MathieuDerelle** [BorisMoore/jsrender#355]
and more generally, I have not found a changelog in this repo.
Is there one ?

**Comment by BorisMoore** [comment]
No, that series of releases had no significant breaking changes. (Other than a couple in advanced APIs which you were unlikely to be using).

Each commit has a commit message/release notes, specifying the changes and indicating any breaking changes. See https://github.com/BorisMoore/jsrender/commits/master. Click on [...] to expand the release notes.

Or look at them separately like this: https://github.com/BorisMoore/jsrender/commit/19a0d0446dac64a6b2ff96822ab33a39c23bd97d.

**Comment by BorisMoore** [comment]
@MathieuDerelle  - I didn't hear back from you. Closing this issue.
