### ISSUE TITLE
Please provide a good documentation on how to use this in Angular 8+ or React 9+ versions

### ISSUE THREAD

**Issue by pavangayakwad** [BorisMoore/jsrender#364]
Despite default data templating parsers of Angular or React, There are many use-cases where application needs to offer custom report templating system to users where they can write their own HTML report format against the JSON data they receive. 

It would be a great help if the development team of JsRender offer a good step-by-step official documentation on how to use JsRender or JsView engines in these (Angular or React) javascript based frameworks/libraries.

Thanks.

**Comment by BorisMoore** [comment]
I agree that this could be helpful, ideally. But it would require someone first to gain sufficient knowledge/expertise of Angular and React, (and one could ask the same for other frameworks such as Vue), before then writing the new additional documentation. I don't currently have time and resources for that, so it is beyond the current scope for JsRender/JsViews documentation, unless someone else is able to contribute the appropriate content...

**Comment by BorisMoore** [comment]
Closing this issue for now.
