### ISSUE TITLE
$(...).render is not a function

### ISSUE THREAD

**Issue by yellareddy-allcloud** [BorisMoore/jsrender#369]
<table class="table table-bordered table-condensed">
    <thead>
      <tr>
        <th>
          <a onclick="addTabRow()" href="#"><i class="fa fa-plus-square fa-lg"></i></a>
          @*<a id="addsec" href="#">Add</a>*@

        </th>
        <th>Order</th>
        <th>Name</th>
        <th>Sub Section(s)</th>
      </tr>
    </thead>
    <tbody id="person"></tbody>
  </table>

  <script id="tabsTemplate" type="text/x-jsrender">
    {{for TabInfos tmpl='#trTabTemplate' /}}
  </script>
  <script id="trTabTemplate" type="text/x-jsrender">
    <tr id="tabOrder{{:#index}}">
      <td>
        <a onclick="delTabRow({{:#index}})" href="#"><i class="fa fa-minus-square fa-lg"></i></a>
      </td>
      <td>
        <input name="TabInfos[{{:#index}}].Order" value="{{:Order}}" class="form-control input-sm" style="width:30px;" />
      </td>
      <td>
        <input name="TabInfos[{{:#index}}].Name" value="{{:Name}}" class="form-control input-sm" style="width:125px;" />
      </td>
    </tr>
  </script>

when am trying to click Add option, adding new row as like as below :

function addTabRow() {

      debugger;

      JqueryAjaxCall('@Url.Action("AddTabRow", "Home")', 'JSON', $("#tblTabs *").serialize(), 'Post', false, function (resp) {

        debugger;

        $("#tblTabs").html(
          $("#tabsTemplate").render(resp.RenderMasterUI)
        );
      
      });
    }

throwing .render is not a function

**Comment by BorisMoore** [comment]
If you load jquery.js and then jsrender.js (or jsviews.js), then '$(...).render' will be a function. 

Are you doing something in 'JqueryAjaxCall' (or in the callback ) which is somehow unloading jsrender.js, or reloading the whole page without jsrender.js?

At any rate this does not correspond to a known bug in jsrender.js, so resolving as N/A for now. 

If you still have a problem, can you post a complete sample (on jsfiddle for example) showing the issue?  

Thanks.
