### ISSUE TITLE
Target a container in parent template from {{for}} in child template?

### ISSUE THREAD

**Issue by rcollette** [BorisMoore/jsrender#81]
This may be more of an enhancement than a bug.   Looking through all the examples I could not find a way of doing the following, but the use case does not seem like an outlier to me.   I have a composite object structure of 
Questions/Question/Answers/Answer/Questions.

questionTemplate is the root template.

    <script id="questionTemplate" type="text/x-jquery-tmpl">
        <div class="question" data-questionId="{{=Id}}">
            <span class="question">{{=Text}}</span><br/>
            <span class="answers">     
            {{each Answers tmpl="#answerTemplate"}}            
            </span>
            <div id="childQuestions{{=Id}}"></div>
        </div>
    </script>
    <script id="childQuestionTemplate" type="text/x-jquery-tmpl">
        <div class="question child" data-questionId="{{=Id}}" style="visibility:hidden;">
            <span class="question">{{=Text}}</span><br/>
            <span class="answers">     
            {{each Answers tmpl="#answerTemplate"}}            
            </span>
            <div id="childQuestions{{=Id}}"></div>
        </div>
    </script>
    <script id="answerTemplate" type="text/x-jquery-tmpl">
        <input type="radio" name="Question{{=$parent.parent.data.Id}}" value="{{=Id}}" data-questionId="{{=$parent.parent.data.Id}}" class="answer">{{=Text}}</input><br/>        
        
        {{each ChildQuestions tmpl="#childQuestionTemplate"}}
    </script>
    <div id="questionList">
    </div>

Ideally, I would not want to have to use an HTML container element in the parent because that forces structure in support of the rendering process.  Some sort of place holder jsRender tag  (eg.  {{%myPlaceHolderName}} ) would be ideal.

**Comment by BorisMoore** [comment]
Closing "After V1.0" issues for now - to reopen as appropriate.
