### ISSUE TITLE
Using {{if}} to manage conditional markup attributes

### ISSUE THREAD

**Issue by govis** [BorisMoore/jsrender#95]
Hi Boris,

I have conditional attributes such as style="display:none;", checked="checked", etc
so my template looks something like:

< tag {{if some condition}}>{{:Field}}{{else}}style="display:none;">{{/if}}< /tag>

This was working fine in jquery-tmpl, but jsRender seems to be inserting < /TD>
< TD undefined[2]-- < /TD>

Is there a way I can turn it off somehow or there is a better alternative?

Thanks again.

**Comment by mattparishdev** [comment]
Would it be possible for someone to provide a specific example for showing how to conditionally set the _checked_ attribute on an input tag of type "checkbox"? I can't seem to get this to work with `{{if}}` statements...

Here is the code I am trying to use:

`<input type="checkbox" {{if ObjectOptionCode == true}}checked{{/if}} disabled="disabled" />`

Thanks in advance for your help!

**Comment by BorisMoore** [comment]
That should work. Can you put it into a jsfiddle, so I can look at what you might be doing wrong elsewhere - in your data, or your code??

**Comment by mattparishdev** [comment]
Boris,

My apologies for not getting back to you sooner. After going through some
more testing, it appears that this did, indeed, work. The thing that was
troubling me was that Visual Studio intellisense does not like the syntax
when mixed with ASP.NET MVC Razor views, so there are consistent "errors"
shown that aren't actually errors.

Thanks for your response!

Matt Parish <https://www.linkedin.com/in/mattparishdev/>
Game Developer & Designer, Software Developer
816.462.7847

**Comment by BorisMoore** [comment]
Thanks for letting me know.
