### ISSUE TITLE
#Index within {{for}} or {{if}} blocks adds underscore to value (By Design!)

### ISSUE THREAD

**Issue by keithbeller** [BorisMoore/jsrender#96]
Here is an example...

Example deleted, since the issue is addressed below...

**Comment by francissalvamantePTX** [comment]
I'm using {{:#index}} to get current index of a data in the iteration {{for}}...{{/for}}. But every time that I try to compare it, [e.g. {{(:#index+1)<10}}] it has an error. Am I doing things incorrectly? Or :#index doesn't support comparison

**Comment by BorisMoore** [comment]
`{{:` is a tag, so you can't break it with a paren. http://www.jsviews.com/#assigntag.
It is `{{:expression}}`

In your case `{{:#index+1<10}}` or  `{{:(#index+1)<10}}`

**Comment by francissalvamantePTX** [comment]
I fixed it a while ago already. I just used #getIndex(). So my loop looks something like this
{{for <data> ~index=#getIndex() ... }}
{{if ~index<ops}}
{{/if}}
{{/for}}

I fixed it by going through jsvies.com :)

**Comment by BorisMoore** [comment]
OK - not sure why you just posted it 15 minutes ago if you had fixed it. Did fixing it "a while go" mean less than 15 minutes ago??

**Comment by francissalvamantePTX** [comment]
Oh sorry sir. It was just that I was trying to fix it as well while waiting for your response. Thank you so much for your response and time sir

**Comment by BorisMoore** [comment]
That's OK - no problem...

**Comment by francissalvamantePTX** [comment]
Quick question, is the output of {{:#index}} and {{:#getIndex()}} equal?

**Comment by BorisMoore** [comment]
Yes, but see explanation here: http://www.jsviews.com/#getindex

**Comment by kmohideen-xybion** [comment]
{{:docfilename}} its value is Testing.txt
I need to do substring so I can get "txt" in JSrenderI

**Comment by BorisMoore** [comment]
@kmohideen-xybion:

You can actually do	

    {{:docfilename.substring(docfilename.indexOf(".")+1)}}

(See [Paths and expressions](https://www.jsviews.com/#paths))

But probably a better approach would be to use a [helper](https://www.jsviews.com/#helpers)

```
$.views.helpers({
  fileExt: function(val) {
    return val.substring(val.indexOf(".")+1);
  }
});
```

with

    {{:~fileExt(docfilename)}}

or a [converter](https://www.jsviews.com/#converters):

```
$.views.converters({
  fileExt: function(val) {
    return val.substring(val.indexOf(".")+1);
  }
});
```

with

    {{fileExt:docfilename}}
